name: huoon
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  provider: ^6.1.2
  intl: ^0.19.0
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  get: ^4.6.6
  shared_preferences: ^2.3.3
  flutter_facebook_auth: 6.0.4
  go_router: ^14.6.0
  google_sign_in: ^6.2.2
  local_auth: ^2.3.0
  signals: ^5.5.0
  avatar_stack: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  table_calendar: ^3.1.2
  file_picker: ^8.1.4
  animate_do: ^3.3.4
  sign_in_button: ^3.2.0
  google_fonts: ^6.2.1
  # flutter_sound: ^9.17.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  fl_chart: ^0.69.2
  firebase_auth: ^5.4.1
  flutter_spinkit: ^5.2.1
  material_symbols_icons: ^4.2801.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter_native_splash:
  color: "#f0f8ff"
  image: assets/splash/huoon_splash.jpg
  fullscreen: true

flutter:

  uses-material-design: true
  generate: true
  assets:
    # Agrega aquí otros idiomas que estés usando
    - lib/l10n/app_en.arb
    - lib/l10n/app_es.arb
    - lib/l10n/app_pt.arb
    - assets/env.prod.json
    - assets/env.dart
    - assets/people/default.jpg
    - assets/splash/huoon_splash.jpg
    - assets/images/icon-Huoon.jpg
    - assets/images/icon-Huoon-transp.jpg
    - assets/gif/writing.gif 
    - assets/images/test/special_offer.jpg
    - assets/images/test/pan-integral.jpeg
    - assets/images/test/pan-queijo.jpeg
    - assets/images/test/pizza-cubana.jpeg
    - assets/images/test/bolo-chocolate.jpeg
    - assets/images/test/negocio.jpg

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Matemasie
      fonts:
        - asset: assets/fonts/Matemasie-Regular.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf  

