// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQfpMUMm9C6-0lTx0dfjJG3HNTJ1LJ2g',
    appId: '1:103032513467:android:ba0306749b1c12a8bdda9e',
    messagingSenderId: '103032513467',
    projectId: 'huoon-app-flutter',
    storageBucket: 'huoon-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmq6F0LMXo3bKOa8aErvskfxETmLfNK8',
    appId: '1:103032513467:ios:9834c8ad7238df3fbdda9e',
    messagingSenderId: '103032513467',
    projectId: 'huoon-app-flutter',
    storageBucket: 'huoon-app-flutter.firebasestorage.app',
    androidClientId: '103032513467-v8p1r65kf0g0np8amjvs6furar59o98p.apps.googleusercontent.com',
    iosClientId: '103032513467-4k144l8spb0dngsssnbequ880f87p4sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.huoon',
  );
}
